[versions]

activity = "1.9.0"
android-gradle-plugin = "8.5.1"
appcompat = "1.7.0"
constraintlayout = "2.1.4"
core-ktx = "1.13.1"
espresso-core = "3.6.1"
generativeai = "0.7.0"
google-auth = "21.2.0"
gridlayout = "1.0.0"
junit = "4.13.2"
junit-ext = "1.2.1"
kotlin-gradle-plugin = "1.9.22"
material = "1.12.0"
navigation = "2.7.7"
splashscreen = "1.0.1"
camerax = "1.3.4"
tensorflow-lite = "0.4.4"
gson = "2.10.1"

[libraries]

activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
generativeai = { group = "com.google.ai.client.generativeai", name = "generativeai", version.ref = "generativeai" }
google-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "google-auth" }
gridlayout = { group = "androidx.gridlayout", name = "gridlayout", version.ref = "gridlayout" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-ext = { group = "androidx.test.ext", name = "junit", version.ref = "junit-ext" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
camerax-core = { group = "androidx.camera", name = "camera-core", version.ref = "camerax" }
camerax-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camerax" }
camerax-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax" }
camerax-view = { group = "androidx.camera", name = "camera-view", version.ref = "camerax" }
tensorflow-lite-task-vision = { group = "org.tensorflow", name = "tensorflow-lite-task-vision", version.ref = "tensorflow-lite" }
tensorflow-lite-gpu-delegate = { group = "org.tensorflow", name = "tensorflow-lite-gpu-delegate-plugin", version.ref = "tensorflow-lite" }
tensorflow-lite = { group = "org.tensorflow", name = "tensorflow-lite", version = "2.12.0"}
tensorflow-lite-gpu = { group = "org.tensorflow", name = "tensorflow-lite-gpu", version = "2.12.0"}
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[plugins]

android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-gradle-plugin" }
